/**
 * Procedural Forge — mesh generation + dual export strings.
 * Story-relevant scene meshes via sceneMeshes.ts (vehicle, path, crowd, vessel…).
 */

import type {
  ActiveConditions,
  EvidenceScore,
  MeshPartSpec,
  ProceduralAsset,
} from '../../types/core'
import { MODEL_DISCLAIMER, uid } from '../../types/core'
import { buildSceneParts } from './sceneMeshes'

export interface GenerateInput {
  name: string
  assetType: string
  description: string
  conditions: ActiveConditions | null
  score?: EvidenceScore
  verifiability?: ProceduralAsset['verifiability']
  reasoning?: string[]
  flags?: string[]
  relatedClaimHint?: string
  sourceIds?: string[]
  importance?: ProceduralAsset['importance']
  accentColor?: string
}

function applyAccent(parts: MeshPartSpec[], accent?: string): MeshPartSpec[] {
  if (!accent) return parts
  return parts.map((p) => {
    if (p.id === 'ground' || p.primitive === 'plane') return p
    // Accent hero parts (lens, core, hood, entry, stamp, heat, label, rotors, pin)
    if (
      /lens|core|hood|entry|stamp|heat|label|rotor|pin|cam-lens|path-pin|veh-hood/.test(p.id)
    ) {
      return { ...p, color: accent }
    }
    return p
  })
}

function buildParts(assetType: string, conditions: ActiveConditions | null): MeshPartSpec[] {
  return buildSceneParts(assetType, conditions)
}

function applyDeploy(parts: MeshPartSpec[], progress: number): MeshPartSpec[] {
  const t = Math.min(1, Math.max(0, progress))
  return parts.map((p) => {
    if (!p.hinge) return p
    const deg = p.hinge.restDeg + (p.hinge.maxDeg - p.hinge.restDeg) * t
    const rad = (deg * Math.PI) / 180
    const rotation: [number, number, number] = [...p.rotation]
    if (p.hinge.axis === 'x') rotation[0] = rad
    if (p.hinge.axis === 'y') rotation[1] = rad
    if (p.hinge.axis === 'z') rotation[2] = p.rotation[2] + rad
    return { ...p, rotation }
  })
}

export function emitUnityCSharp(asset: ProceduralAsset): string {
  const lines: string[] = [
    '// Auto-generated by Nexus Procedural Forge — story scene mesh',
    '// ' + MODEL_DISCLAIMER,
    'using UnityEngine;',
    '',
    `public class ${sanitizeId(asset.name)}Generator : MonoBehaviour`,
    '{',
    '    [Range(0f, 1f)] public float deployProgress = 0f;',
    '    void Start() { Build(); }',
    '',
    '    public void Build()',
    '    {',
    '        var root = new GameObject("NexusAsset");',
  ]
  for (const p of asset.parts) {
    if (p.primitive === 'plane') continue
    lines.push(`        // ${p.name}`)
    lines.push(`        {`)
    lines.push(
      `            var go = GameObject.CreatePrimitive(PrimitiveType.${unityPrimitive(p.primitive)});`,
    )
    lines.push(`            go.name = "${p.name}";`)
    lines.push(`            go.transform.SetParent(root.transform, false);`)
    lines.push(
      `            go.transform.localPosition = new Vector3(${f(p.position[0])}f, ${f(p.position[1])}f, ${f(p.position[2])}f);`,
    )
    lines.push(
      `            go.transform.localScale = new Vector3(${f(p.size[0])}f, ${f(p.size[1])}f, ${f(p.size[2])}f);`,
    )
    lines.push(`        }`)
  }
  lines.push('    }')
  lines.push('}')
  lines.push('')
  lines.push(`// assetType: ${asset.assetType}`)
  if (asset.verifiability) lines.push(`// verifiability: ${asset.verifiability}`)
  return lines.join('\n')
}

export function emitThreeTsx(asset: ProceduralAsset): string {
  const partsJsx = asset.parts
    .map((p) => {
      if (p.primitive === 'plane') {
        return `      <mesh rotation={[${p.rotation.join(', ')}]} position={[${p.position.join(', ')}]}>
        <planeGeometry args={[${p.size[0]}, ${p.size[2]}]} />
        <meshStandardMaterial color="${p.color}" />
      </mesh>`
      }
      const geo =
        p.primitive === 'box'
          ? `<boxGeometry args={[${p.size.join(', ')}]} />`
          : p.primitive === 'sphere'
            ? `<sphereGeometry args={[${p.size[0]}, 16, 16]} />`
            : `<cylinderGeometry args={[${p.size[0]}, ${p.size[0]}, ${p.size[1]}, 12]} />`
      return `      <mesh position={[${p.position.join(', ')}]} rotation={[${p.rotation.join(', ')}]}>
        ${geo}
        <meshStandardMaterial color="${p.color}" />
      </mesh>`
    })
    .join('\n')

  return `/** Auto-generated by Nexus Procedural Forge — ${asset.assetType} */
import { Canvas } from '@react-three/fiber'
import { OrbitControls } from '@react-three/drei'

export function ${sanitizeId(asset.name)}View() {
  return (
    <Canvas camera={{ position: [6, 5, 8], fov: 45 }}>
      <color attach="background" args={['#05070f']} />
      <ambientLight intensity={0.5} />
      <directionalLight position={[8, 14, 6]} intensity={1} />
      <group>
${partsJsx}
      </group>
      <OrbitControls />
    </Canvas>
  )
}
`
}

function unityPrimitive(p: MeshPartSpec['primitive']): string {
  if (p === 'box') return 'Cube'
  if (p === 'sphere') return 'Sphere'
  if (p === 'cylinder') return 'Cylinder'
  return 'Cube'
}

function sanitizeId(name: string): string {
  const s = name.replace(/[^a-zA-Z0-9_]/g, '_') || 'Asset'
  return /^[0-9]/.test(s) ? `A_${s}` : s
}

function f(n: number): string {
  return (Math.round(n * 1000) / 1000).toString()
}

export function generateAsset(input: GenerateInput): ProceduralAsset {
  const now = new Date().toISOString()
  const base = buildParts(input.assetType, input.conditions)
  const parts = applyAccent(base, input.accentColor)
  const score: EvidenceScore = input.score ?? 0
  const draft: ProceduralAsset = {
    id: uid('asset'),
    name: input.name || 'Asset',
    assetType: input.assetType,
    description: input.description,
    version: 1,
    createdAt: now,
    updatedAt: now,
    conditionsSnapshot: input.conditions,
    parts,
    animation: {
      deployProgress: 0,
      drivers: parts
        .filter((p) => p.hinge)
        .map((p) => ({
          partId: p.id,
          param: `hinge.${p.hinge!.axis}`,
          from: p.hinge!.restDeg,
          to: p.hinge!.maxDeg,
        })),
    },
    optimizeNotes: [
      ...(input.reasoning ?? []).slice(0, 4),
      ...(input.flags?.length ? [`Flags: ${input.flags.join(', ')}`] : []),
      MODEL_DISCLAIMER,
    ],
    unityCSharp: '',
    threeTsx: '',
    score,
    verifiability: input.verifiability,
    reasoning: input.reasoning,
    flags: input.flags,
    relatedClaimHint: input.relatedClaimHint,
    sourceIds: input.sourceIds,
    importance: input.importance,
  }
  draft.unityCSharp = emitUnityCSharp(draft)
  draft.threeTsx = emitThreeTsx(draft)
  return draft
}

export function optimizeAsset(asset: ProceduralAsset): ProceduralAsset {
  const notes = [
    'Normalized hinge limits to deploy 0–1.',
    'Preserved story mesh family (not remapped to mast).',
    MODEL_DISCLAIMER,
  ]
  const next: ProceduralAsset = {
    ...asset,
    version: asset.version + 1,
    updatedAt: new Date().toISOString(),
    beforeParts: asset.beforeParts ?? asset.parts,
    optimizeNotes: [...asset.optimizeNotes, ...notes],
    parts: asset.parts.map((p) =>
      p.primitive === 'box' && p.size[0] > 0.2
        ? {
            ...p,
            size: [p.size[0] * 0.99, p.size[1], p.size[2] * 0.99] as [number, number, number],
          }
        : p,
    ),
  }
  next.unityCSharp = emitUnityCSharp(next)
  next.threeTsx = emitThreeTsx(next)
  return next
}

export function setDeployProgress(asset: ProceduralAsset, progress: number): ProceduralAsset {
  const t = Math.min(1, Math.max(0, progress))
  const rest = buildParts(asset.assetType, asset.conditionsSnapshot)
  const hinged = applyDeploy(
    rest.map((r) => {
      const prev = asset.parts.find((p) => p.id === r.id)
      return prev ? { ...r, color: prev.color } : r
    }),
    t,
  )
  const next: ProceduralAsset = {
    ...asset,
    parts: hinged,
    animation: { ...asset.animation, deployProgress: t },
    updatedAt: new Date().toISOString(),
  }
  next.unityCSharp = emitUnityCSharp(next)
  next.threeTsx = emitThreeTsx(next)
  return next
}
